name = "dispoflare"

# workers_dev = true
main = "workers/index.ts"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-03-26"

[vars]
# The necessary secrets are:
# - CLOUDFLARE_API_TOKEN
# - CLOUDFLARE_ACCOUNT_ID
# - SENTRY_DSN
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these

[triggers]
crons = [ "0 */12 * * *" ]
